pipeline {
    agent any
    
    tools {
        maven 'csemaven'
        jdk 'csejava'
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                dir('edupulse_clean') {
                    bat 'mvn clean package -DskipTests'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                // This name 'SonarServer' must match what you typed in Step 3
                withSonarQubeEnv('SonarServer') {
                    dir('edupulse_clean') {
                        bat 'mvn sonar:sonar'
                    }
                }
            }
        }
        
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'edupulse_clean/target/*.jar'
            }
        }
    }
}