pipeline {
    agent any
    
    tools {
        maven 'csemaven'
        jdk 'csejava'
    }
    
    stages {
        stage('Checkout') {
            steps {
                // Pulls the latest code from your GitHub repository
                checkout scm
            }
        }
        
        stage('Build & Test') {
            steps {
                // 'edupulse_clean' is the folder name on your GitHub
                dir('edupulse_clean') {
                    // 'verify' ensures unit tests run and coverage is recorded
                    bat 'mvn clean verify'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarServer') {
                    dir('edupulse_clean') {
                        bat 'mvn sonar:sonar'
                    }
                }
            }
        }
        
        stage('Archive Artifacts') {
            steps {
                // Saves the JAR file inside Jenkins
                archiveArtifacts artifacts: 'edupulse_clean/target/*.jar', allowEmptyArchive: true
            }
        }

        stage('Deploy to AWS with Ansible') {
            steps {
                dir('edupulse_clean') {
                    echo 'Deploying to AWS via Explicit Ubuntu WSL Bridge...'
                    /* -d Ubuntu: Forces Windows to use your specific Linux install.
                       sh -c: Uses the standard shell to execute the command.
                       ANSIBLE_HOST_KEY_CHECKING=False: Prevents the pipeline from hanging on SSH prompts.
                    */
                    bat 'wsl -d Ubuntu sh -c "ANSIBLE_HOST_KEY_CHECKING=False /usr/bin/ansible-playbook -i hosts deploy.yml"'
                }
            }
        }
    }
    
    post {
        success {
            echo 'Congratulations Pinky! The entire pipeline finished successfully.'
            echo 'Your app is live at: http://http://98.91.206.16:8087'
        }
        failure {
            echo 'The pipeline failed. Check the Console Output for details.'
        }
    }
}