pipeline {
    agent any
    
    tools {
        maven 'csemaven'
        jdk 'csejava'
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build & Test') {
            steps {
                // Based on your GitHub screenshot, the pom.xml is in this folder
                dir('edupulse_clean') {
                    bat 'mvn clean verify'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarServer') {
                    dir('edupulse_clean') {
                        bat 'mvn sonar:sonar'
                    }
                }
            }
        }
        
        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: 'edupulse_clean/target/*.jar', allowEmptyArchive: true
            }
        }

        stage('Deploy to AWS with Ansible') {
            steps {
                dir('edupulse_clean') {
                    echo 'Executing Ansible via absolute WSL paths...'
                    /* We are now using /bin/bash instead of just 'bash'.
                       This ensures WSL finds the shell even if the PATH is empty.
                    */
                    bat 'wsl /bin/bash -c "ANSIBLE_HOST_KEY_CHECKING=False /usr/bin/ansible-playbook -i hosts deploy.yml"'
                }
            }
        }
    }
    
    post {
        success {
            echo 'Congratulations Pinky! The entire pipeline finished successfully.'
            echo 'Access your app here: http://100.31.148.55:8087'
        }
        failure {
            echo 'The pipeline failed. Check the Console Output to see the error details.'
        }
    }
}